# Generated by Django 3.1.6 on 2021-04-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodels',
            name='short_url',
            field=models.CharField(default='dhkfrn', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlmodels',
            name='slug',
            field=models.CharField(default='dndken', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlmodels',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
