# Generated by Django 3.1.6 on 2021-04-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210416_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodels',
            name='short_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
