# Generated by Django 3.1.6 on 2021-04-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20210416_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodels',
            name='short_url',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
