# Generated by Django 3.1.6 on 2021-04-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_remove_urlmodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodels',
            name='short_url',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
