# Generated by Django 3.1.6 on 2021-04-18 06:18

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0006_auto_20210417_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodels',
            name='url',
            field=models.CharField(max_length=1000, validators=[shortner.validators.validate_url]),
        ),
    ]
